language: common-lisp
sudo: false

addons:
  apt:
    packages:
      - zip

env:
  global:
    - GAMEKIT_SYSTEM_NAME: deserted
    - GAMEKIT_APPLICATION_PACKAGE: deserted
    - GAMEKIT_APPLICATION_MAIN_CLASS: deserted
    - PATH: ~/bin/:$PATH
    - GAMEKIT_TARGET_PACKAGE: $GAMEKIT_SYSTEM_NAME-x86-64-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip
    - GAMEKIT_BUILD_DIR: /tmp/$GAMEKIT_SYSTEM_NAME
    - secure: "fXdJ4WAG0DUKBagavqAokRpYAlsVosvqYtjA6+g60xukYHfBvRt4F/3Vl9w5E/A8krCs71lOYR2vslI3PjUbmq7BTj5dyyvl3z+ov7X9f3qregLHo9hX4b3UJqDdfIZ/KqwmzKy4OPXiLBhXqiacOtL10+CzdLFnX8ai/ujWnZ9MiCNNgYNP6XW4apy4fbzjjFBPTaL06c9sMmQAySVr5Rhy1w+Mx22FPYCn3quV4DBmFEblBgDeDSvvxWbktAHI/NLHzfXNu/fG4xeyOW8XDSlt4SKsheIcFKCBwUWDj+oOPKMfo0yH+2t7+osRBKfD5FghUlRvBZ4QYxF1uN9NG4Db+GqMjtP/PBvjNzVaJqZwt8KFlMdHanJSl8LUxcxztEdaCHllfJ6iVNkr5CovL4es+v217poKEsiEbUUTiV6OhulCmniP1CwIinHGd930wrMvD+MX+IPY0e+4kR7/Orm6kJH5ZRrWsjr2r4XZqlcMPWzOKO/YhXTcGMS6YBC3C3kiza1i6jyHC2DlI5jMH7gb7UpoV+Ykbq1yCRL5eC7gypibefpUUapaew0RmjXPxGvz/uWXArXwZc1UJMDtVagyOtBtl0yGixiqrlUUAre+Re7QueiBmnaHom1pA2O6CB/GflU0XJv13QAUL4M2A3YThFIe7m0jH4iC2GyDEuE="

branches:
  only:
    - "/^v\\d+(\\.\\d+)+$/"

os:
  - linux
  - osx

install:
  - curl -L http://bodge.borodust.org/files/install.sh | sh

script:
  - >
    lisp $HOME/bodge/scripts/build-experimental-gamekit-system.lisp
    $GAMEKIT_SYSTEM_NAME $GAMEKIT_APPLICATION_PACKAGE $GAMEKIT_APPLICATION_MAIN_CLASS
    $TRAVIS_BUILD_DIR
    $GAMEKIT_BUILD_DIR

before_deploy:
  - mv "$GAMEKIT_BUILD_DIR/$GAMEKIT_SYSTEM_NAME.zip" $GAMEKIT_TARGET_PACKAGE

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $GAMEKIT_TARGET_PACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
